import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

const PDF_UI = {
  en: { question:"Question", generatedSQL:"Generated SQL", chart:"Chart", results:"Results", insight:"Insight", footer:"Generated by Hanalyst - AI Data Analyst", page:"Page", of:"of" },
  ta: { question:"கேள்வி", generatedSQL:"உருவாக்கப்பட்ட SQL", chart:"விளக்கப்படம்", results:"முடிவுகள்", insight:"நுண்ணறிவு", footer:"Hanalyst - AI தரவு பகுப்பாய்வி", page:"பக்கம்", of:"இல்" },
  hi: { question:"प्रश्न", generatedSQL:"जनरेटेड SQL", chart:"चार्ट", results:"परिणाम", insight:"अंतर्दृष्टि", footer:"Hanalyst - AI डेटा विश्लेषक द्वारा निर्मित", page:"पृष्ठ", of:"का" },
  te: { question:"ప్రశ్న", generatedSQL:"రూపొందించిన SQL", chart:"చార్ట్", results:"ఫలితాలు", insight:"అంతర్దృష్టి", footer:"Hanalyst - AI డేటా విశ్లేషకుడు", page:"పేజీ", of:"లో" },
  ml: { question:"ചോദ്യം", generatedSQL:"ജനറേറ്റ് ചെയ്ത SQL", chart:"ചാർട്ട്", results:"ഫലങ്ങൾ", insight:"ഉൾക്കാഴ്ച", footer:"Hanalyst - AI ഡേറ്റ അനലിസ്റ്റ്", page:"പേജ്", of:"/" },
  kn: { question:"ಪ್ರಶ್ನೆ", generatedSQL:"ರಚಿಸಲಾದ SQL", chart:"ಚಾರ್ಟ್", results:"ಫಲಿತಾಂಶಗಳು", insight:"ಒಳನೋಟ", footer:"Hanalyst - AI ಡೇಟಾ ವಿಶ್ಲೇಷಕ", page:"ಪುಟ", of:"/" },
  bn: { question:"প্রশ্ন", generatedSQL:"তৈরি SQL", chart:"চার্ট", results:"ফলাফল", insight:"অন্তর্দৃষ্টি", footer:"Hanalyst - AI ডেটা বিশ্লেষক", page:"পৃষ্ঠা", of:"এর" },
  gu: { question:"પ્રશ્ન", generatedSQL:"જનરેટ થયેલ SQL", chart:"ચાર્ટ", results:"પરિણામો", insight:"આંતરદૃષ્ટિ", footer:"Hanalyst - AI ડેટા વિશ્લેષક", page:"પૃષ્ઠ", of:"નો" },
  pa: { question:"ਸਵਾਲ", generatedSQL:"ਬਣਾਈ SQL", chart:"ਚਾਰਟ", results:"ਨਤੀਜੇ", insight:"ਸੂਝ", footer:"Hanalyst - AI ਡੇਟਾ ਵਿਸ਼ਲੇਸ਼ਕ", page:"ਪੰਨਾ", of:"ਦਾ" },
  ar: { question:"السؤال", generatedSQL:"SQL المُنشأ", chart:"المخطط", results:"النتائج", insight:"رؤية", footer:"تم الإنشاء بواسطة Hanalyst", page:"صفحة", of:"من" },
  fr: { question:"Question", generatedSQL:"SQL généré", chart:"Graphique", results:"Résultats", insight:"Aperçu", footer:"Généré par Hanalyst - Analyste IA", page:"Page", of:"sur" },
  de: { question:"Frage", generatedSQL:"Generiertes SQL", chart:"Diagramm", results:"Ergebnisse", insight:"Einblick", footer:"Erstellt von Hanalyst - KI-Datenanalyst", page:"Seite", of:"von" },
  ja: { question:"質問", generatedSQL:"生成されたSQL", chart:"グラフ", results:"結果", insight:"洞察", footer:"Hanalyst - AIデータアナリストによって生成", page:"ページ", of:"/" },
  zh: { question:"问题", generatedSQL:"生成的SQL", chart:"图表", results:"结果", insight:"洞察", footer:"由Hanalyst - AI数据分析师生成", page:"第", of:"页" },
};

async function captureChart() {
  // Try multiple selectors in order of preference
  const selectors = [".chart-body", ".chart-box", ".recharts-wrapper", ".recharts-surface"];
  for (const sel of selectors) {
    const el = document.querySelector(sel);
    if (el && el.offsetWidth > 0 && el.offsetHeight > 0) {
      try {
        const canvas = await html2canvas(el, {
          backgroundColor: "#ffffff",
          scale: 2,
          useCORS: true,
          logging: false,
          allowTaint: true
        });
        if (canvas.width > 10 && canvas.height > 10) {
          return canvas;
        }
      } catch (e) {
        console.log("Capture failed for " + sel + ":", e);
      }
    }
  }
  return null;
}

export async function exportToPDF(question, sql, data, insight, lang = "en") {
  const t = PDF_UI[lang] || PDF_UI.en;
  const doc = new jsPDF();

  doc.setFillColor(16, 163, 127);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("Hanalyst Report", 14, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleDateString(), 160, 14);

  let y = 32;

  // Question
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(t.question, 14, y);
  y += 6;
  doc.setFillColor(241, 245, 249);
  const questionLines = doc.splitTextToSize(question || "N/A", 175);
  doc.rect(12, y - 3, 185, questionLines.length * 5.5 + 6, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(questionLines, 16, y + 2);
  y += questionLines.length * 5.5 + 12;

  // SQL
  if (sql) {
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(t.generatedSQL, 14, y);
    y += 6;
    const sqlLines = doc.splitTextToSize(sql, 173);
    const sqlBoxH = sqlLines.length * 4.5 + 10;
    doc.setFillColor(245, 245, 245);
    doc.rect(12, y - 3, 185, sqlBoxH, "F");
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.rect(12, y - 3, 185, sqlBoxH, "S");
    doc.setDrawColor(16, 163, 127);
    doc.setLineWidth(2);
    doc.line(12, y - 3, 12, y - 3 + sqlBoxH);
    doc.setLineWidth(0.3);
    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(20, 100, 60);
    doc.text(sqlLines, 16, y + 2);
    y += sqlBoxH + 12;
  }

  // Chart — wait longer for Recharts to fully render
  const canvas = await captureChart();
  if (canvas) {
    if (y > 180) { doc.addPage(); y = 20; }
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(t.chart, 14, y);
    y += 6;
    const imgData = canvas.toDataURL("image/png");
    const imgW = 182;
    const imgH = Math.round((canvas.height / canvas.width) * imgW);
    doc.addImage(imgData, "PNG", 14, y, imgW, imgH);
    y += imgH + 12;
  }

  // Results table
  if (data && data.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(t.results, 14, y);
    y += 4;
    const headers = Object.keys(data[0]);
    const rows = data.map(row => Object.values(row).map(v => typeof v === "number" ? v.toLocaleString() : String(v ?? "")));
    autoTable(doc, {
      startY: y,
      head: [headers],
      body: rows,
      theme: "grid",
      headStyles: { fillColor: [16, 163, 127], textColor: 255, fontSize: 9, fontStyle: "bold" },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 }
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  // Insight
  if (insight) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(t.insight, 14, y);
    y += 6;
    const insightLines = doc.splitTextToSize(insight, 173);
    const insightBoxH = insightLines.length * 5 + 10;
    doc.setFillColor(240, 253, 248);
    doc.rect(12, y - 3, 185, insightBoxH, "F");
    doc.setDrawColor(16, 163, 127);
    doc.setLineWidth(2);
    doc.line(12, y - 3, 12, y - 3 + insightBoxH);
    doc.setLineWidth(0.3);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(15, 110, 86);
    doc.text(insightLines, 16, y + 2);
    y += insightBoxH + 8;
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(245, 245, 245);
    doc.rect(0, 285, 210, 12, "F");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text(t.footer, 14, 292);
    doc.text(t.page + " " + i + " " + t.of + " " + pageCount, 185, 292, { align: "right" });
  }

  doc.save("hanalyst_report.pdf");
}
