import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

export async function exportToPDF(question, sql, data, insight) {
  const doc = new jsPDF();

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFillColor(16, 163, 127);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("Hanalyst Report", 14, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleDateString(), 160, 14);

  let y = 32;

  // ── Question ──────────────────────────────────────────────────────────────
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Question", 14, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  const questionLines = doc.splitTextToSize(question || "N/A", 175);
  doc.rect(12, y - 3, 185, questionLines.length * 5.5 + 6, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(questionLines, 16, y + 2);
  y += questionLines.length * 5.5 + 12;

  // ── SQL ───────────────────────────────────────────────────────────────────
  if (sql) {
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Generated SQL", 14, y);
    y += 6;

    const sqlLines = doc.splitTextToSize(sql, 173);
    const sqlBoxH = sqlLines.length * 4.5 + 10;
    doc.setFillColor(245, 245, 245);
    doc.rect(12, y - 3, 185, sqlBoxH, "F");
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.rect(12, y - 3, 185, sqlBoxH, "S");
    // Green left accent line
    doc.setDrawColor(16, 163, 127);
    doc.setLineWidth(2);
    doc.line(12, y - 3, 12, y - 3 + sqlBoxH);
    doc.setLineWidth(0.3);

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(20, 100, 60);
    doc.text(sqlLines, 16, y + 2);
    y += sqlBoxH + 12;
  }

  // ── Chart ─────────────────────────────────────────────────────────────────
  const chartEl = document.querySelector(".chart-body");
  if (chartEl) {
    try {
      if (y > 180) { doc.addPage(); y = 20; }

      doc.setTextColor(30, 30, 30);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Chart", 14, y);
      y += 6;

      const canvas = await html2canvas(chartEl, {
        backgroundColor: "#1a1a1a",
        scale: 2,
        useCORS: true,
        logging: false
      });

      const imgData = canvas.toDataURL("image/png");
      const imgW = 182;
      const imgH = Math.round((canvas.height / canvas.width) * imgW);

      doc.addImage(imgData, "PNG", 14, y, imgW, imgH);
      y += imgH + 12;
    } catch (e) {
      console.log("Chart capture failed:", e);
    }
  }

  // ── Results table ─────────────────────────────────────────────────────────
  if (data && data.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Results", 14, y);
    y += 4;

    const headers = Object.keys(data[0]);
    const rows = data.map(row =>
      Object.values(row).map(v =>
        typeof v === "number" ? v.toLocaleString() : String(v ?? "")
      )
    );

    autoTable(doc, {
      startY: y,
      head: [headers],
      body: rows,
      theme: "grid",
      headStyles: { fillColor: [16, 163, 127], textColor: 255, fontSize: 9, fontStyle: "bold" },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 }
    });

    y = doc.lastAutoTable.finalY + 12;
  }

  // ── Insight ───────────────────────────────────────────────────────────────
  if (insight) {
    if (y > 240) { doc.addPage(); y = 20; }

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Insight", 14, y);
    y += 6;

    const insightLines = doc.splitTextToSize(insight, 173);
    const insightBoxH = insightLines.length * 5 + 10;

    doc.setFillColor(240, 253, 248);
    doc.rect(12, y - 3, 185, insightBoxH, "F");
    doc.setDrawColor(16, 163, 127);
    doc.setLineWidth(2);
    doc.line(12, y - 3, 12, y - 3 + insightBoxH);
    doc.setLineWidth(0.3);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(15, 110, 86);
    doc.text(insightLines, 16, y + 2);
    y += insightBoxH + 8;
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(245, 245, 245);
    doc.rect(0, 285, 210, 12, "F");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by Hanalyst - AI Data Analyst", 14, 292);
    doc.text("Page " + i + " of " + pageCount, 185, 292, { align: "right" });
  }

  doc.save("hanalyst_report.pdf");
}